### ISSUE TITLE
Changes for running on Linux

### ISSUE THREAD

**Issue by nothingTVatYT** [Menotdan/PLCT#1]
For the record, this is what we changed to make it work:
```
diff --git a/Source/Engine/Content/Factories/IAssetFactory.h b/Source/Engine/Content/Factories/IAssetFactory.h
index e7417c9dd..70efd34aa 100644
--- a/Source/Engine/Content/Factories/IAssetFactory.h
+++ b/Source/Engine/Content/Factories/IAssetFactory.h
@@ -20,13 +20,20 @@ class FLAXENGINE_API IAssetFactory
     /// <summary>
     /// Gets the all registered assets factories. Key is asset typename, value is the factory object.
     /// </summary>
+    /*
     static Collection& Get()
     {
         static Collection Factories(1024);
         return Factories;
-    }
+    }*/
 
 public:
+    static Collection Factories;
+    static Collection& Get()
+    {
+        return Factories;
+    }
+
     /// <summary>
     /// Finalizes an instance of the <see cref="IAssetFactory"/> class.
     /// </summary>
```

**Comment by Menotdan** [comment]
> For the record, this is what we changed to make it work:
> 
> ```
> diff --git a/Source/Engine/Content/Factories/IAssetFactory.h b/Source/Engine/Content/Factories/IAssetFactory.h
> index e7417c9dd..70efd34aa 100644
> --- a/Source/Engine/Content/Factories/IAssetFactory.h
> +++ b/Source/Engine/Content/Factories/IAssetFactory.h
> @@ -20,13 +20,20 @@ class FLAXENGINE_API IAssetFactory
>      /// <summary>
>      /// Gets the all registered assets factories. Key is asset typename, value is the factory object.
>      /// </summary>
> +    /*
>      static Collection& Get()
>      {
>          static Collection Factories(1024);
>          return Factories;
> -    }
> +    }*/
>  
>  public:
> +    static Collection Factories;
> +    static Collection& Get()
> +    {
> +        return Factories;
> +    }
> +
>      /// <summary>
>      /// Finalizes an instance of the <see cref="IAssetFactory"/> class.
>      /// </summary>
> ```

Why'd you make an issue here? lol
Making a PR for it on Flax now.

**Comment by nothingTVatYT** [comment]
I just needed a place to document my patch before it gets lost and I thought why not spamming your clean repo?

**Comment by Menotdan** [comment]
This was fixed lol
